webpack config
htmlacademy-ecmascript/1018179-cinemaddict-13 pull request #2
Opened 2020-11-18 18:58 UTC by PavelCraze

2020-11-18 20:06 UTC, dean992008 requested changes

2020-11-18 20:06 UTC, dean992008 commented on webpack.config.js
> +    filename: 'bundle.js',
bundle.js нужно подключить в index.html

2020-11-19 18:42 UTC, dean992008 commented on webpack.config.js
> +    filename: 'bundle.js',
Сделал немного неправильно. Корень сервера это public, от него нужно и прописывать путь. Правильно прописать: 
```
<script src="bundle.js"></script>
```

2020-11-19 18:45 UTC, PavelCraze commented on webpack.config.js
> +    filename: 'bundle.js',
Понял)

2020-11-19 18:58 UTC, merged